[[core]]
opcode = "add"
dst = "Register"
src1 = "Register"
src2 = "Register"
translation = ""

[[core]]
opcode = "rsh"
dst = "Register"
src1 = "Register"
src2 = "None"
translation = ""

[[core]]
opcode = "lod"
dst = "Register"
src1 = "Register"
src2 = "None"
translation = ""

[[core]]
opcode = "str"
dst = "Register"
src1 = "Register"
src2 = "None"
translation = ""

[[core]]
opcode = "bge"
dst = "Register"
src1 = "Register"
src2 = "Register"
translation = ""

[[core]]
opcode = "nor"
dst = "Register"
src1 = "Register"
src2 = "Register"
translation = ""

[[core]]
opcode = "imm"
dst = "Register"
src1 = "Constant"
src2 = "None"
translation = ""

## Basic Instructions

# ADD
[[all]]
opcode = "add"
dst = "Register"
src1 = "Register"
src2 = "Constant"
translation = '''
imm {1} {c}
add {a} {b} {1}
'''

[[all]]
opcode = "add"
dst = "Register"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {b}
add {a} {1} {c}
'''

[[all]]
opcode = "add"
dst = "Register"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {b}
imm {2} {c}
add {a} {1} {2}
'''

# RSH
[[all]]
opcode = "rsh"
dst = "Register"
src1 = "Constant"
src2 = "None"
translation = '''
imm {1} {b}
rsh {a} {1}
'''

# LOD
[[all]]
opcode = "lod"
dst = "Register"
src1 = "Constant"
src2 = "None"
translation = '''
imm {1} {b}
lod {a} {1}
'''

[[all]]
opcode = "lod"
dst = "PC"
src1 = "Register"
src2 = "None"
translation = '''
lod {1} {b}
jmp {1}
'''

[[all]]
opcode = "lod"
dst = "PC"
src1 = "Constant"
src2 = "None"
translation = '''
lod {1} {b}
jmp {1}
'''

# STR
[[all]]
opcode = "str"
dst = "Register"
src1 = "Constant"
src2 = "None"
translation = '''
imm {1} {b}
str {a} {1}
'''

[[all]]
opcode = "str"
dst = "Constant"
src1 = "Register"
src2 = "None"
translation = '''
imm {1} {a}
str {1} {b}
'''

[[all]]
opcode = "str"
dst = "Constant"
src1 = "Constant"
src2 = "None"
translation = '''
imm {1} {a}
imm {2} {b}
str {1} {2}
'''

# BGE
[[all]]
opcode = "bge"
dst = "Register"
src1 = "Register"
src2 = "Constant"
translation = '''
imm {1} {c}
bge {a} {b} {1}
'''

[[all]]
opcode = "bge"
dst = "Register"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {b}
bge {a} {1} {c}
'''

[[all]]
opcode = "bge"
dst = "Constant"
src1 = "Register"
src2 = "Register"
translation = '''
imm {1} {a}
bge {1} {b} {c}
'''

[[all]]
opcode = "bge"
dst = "Constant"
src1 = "Register"
src2 = "Constant"
translation = '''
imm {1} {a}
imm {2} {c}
bge {1} {b} {2}
'''

[[all]]
opcode = "bge"
dst = "Constant"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {a}
imm {2} {b}
bge {1} {2} {c}
'''

# NOR
[[all]]
opcode = "nor"
dst = "Register"
src1 = "Register"
src2 = "Constant"
translation = '''
imm {1} {c}
nor {a} {b} {1}
'''

[[all]]
opcode = "nor"
dst = "Register"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {b}
nor {a} {1} {c}
'''

# SUB
[[all]]
opcode = "sub"
dst = "Register"
src1 = "Register"
src2 = "Register"
translation = '''
not {1} {c}
add {a} {b} {1}
inc {a} {a}
'''

[[all]]
opcode = "sub"
dst = "Register"
src1 = "Register"
src2 = "Constant"
translation = '''
imm {1} {c}
sub {a} {b} {1}
'''

[[all]]
opcode = "sub"
dst = "Register"
src1 = "Constant"
src2 = "Register"
translation = '''
imm {1} {b}
sub {a} {1} {c}
'''

[[all]]
opcode = "sub"
dst = "Register"
src1 = "Constant"
src2 = "Constant"
translation = '''
imm {1} {b}
imm {2} {c}
sub {a} {1} {2}
'''

# JMP
[[all]]
opcode = "jmp"
dst = "Any"
src1 = "None"
src2 = "None"
translation = '''
bge {a} R0 R0
'''

# MOV
[[all]]
opcode = "mov"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
add {a} {b} R0
'''

# NOP
[[all]]
opcode = "nop"
dst = "None"
src1 = "None"
src2 = "None"
translation = '''
mov R0 R0
'''

# IMM - FIXME: This is pain
# [[all]]
# opcode = "imm"
# dst = "Any"
# src1 = "Any"
# src2 = "None"
# translation = '''
# add {a} {b} R0
# '''

# LSH
[[all]]
opcode = "lsh"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
add {a} {b} {b}
'''

# INC
[[all]]
opcode = "inc"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
add {a} {b} 1
'''

# DEC
[[all]]
opcode = "dec"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
not {1} R0
add {a} {b} {1}
'''

# NEG
[[all]]
opcode = "neg"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
not {a} {b}
inc {a} {a}
'''

# AND
[[all]]
opcode = "and"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
not {1} {b}
not {2} {c}
nor {a} {1} {2}
'''

# OR
[[all]]
opcode = "or"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
nor {a} {b} {c}
not {a} {a}
'''

# NOT
[[all]]
opcode = "not"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
nor {a} {b} R0
'''

# XNOR
[[all]]
opcode = "xnor"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
and {a} {b} {c}
nor {1} {b} {c}
nor {a} {a} {1}
not {a} {a}
'''

# XOR
[[all]]
opcode = "xor"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
and {a} {b} {c}
nor {1} {b} {c}
nor {a} {a} {1}
'''

# NAND
[[all]]
opcode = "nand"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
not {1} {b}
not {a} {c}
nor {a} {a} {1}
not {a} {a}
'''

# BRL
[[all]]
opcode = "brl"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
bge ~+2 {b} {c}
jmp {a}
'''

# BRG
[[all]]
opcode = "brg"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
bge ~+2 {c} {b}
jmp {a}
'''

# BRE
[[all]]
opcode = "bre"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
bge ~+2 {b} {c}
jmp ~+4
bge ~+2 {c} {b}
jmp ~+2
jmp {a}
'''

# BNE
[[all]]
opcode = "bne"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
bge ~+2 {b} {c}
jmp ~+2
bge ~+2 {c} {b}
jmp {a}
'''

# BOD
[[all]]
opcode = "bod"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
add {1} {b} 1
bge ~+2 {1} 1
jmp ~+3
jmp {a}
'''

# BEV
[[all]]
opcode = "bev"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
add {1} {b} 1
bge ~+2 {1} 1
jmp {a}
'''

# BLE
[[all]]
opcode = "ble"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
bge {a} {c} {b}
'''

# BRZ
[[all]]
opcode = "brz"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
bge ~+2 {b} 1
jmp {a}
'''

# BNZ
[[all]]
opcode = "bnz"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
bge {a} {b} 1
'''

# BRN
[[all]]
opcode = "brn"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
bge {a} {b} {m}
'''

# BRP
[[all]]
opcode = "brp"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
bge ~+2 {b} {m}
jmp {a}
'''

# PSH
[[all]]
opcode = "psh"
dst = "Any"
src1 = "None"
src2 = "None"
translation = '''
dec SP SP
str SP {a}
'''

# POP
[[all]]
opcode = "pop"
dst = "Any"
src1 = "None"
src2 = "None"
translation = '''
lod {a} SP
inc SP SP
'''

# CAL
[[all]]
opcode = "cal"
dst = "Memory"
src1 = "None"
src2 = "None"
translation = '''
psh ~+2
jmp {a}
'''

# RET
[[all]]
opcode = "ret"
dst = "None"
src1 = "None"
src2 = "None"
translation = '''
pop {1}
jmp {1}
'''

# HLT
[[all]]
opcode = "hlt"
dst = "None"
src1 = "None"
src2 = "None"
translation = '''
jmp ~+0
'''

# CPY
[[all]]
opcode = "cpy"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
lod {1} {b}
str {a} {1}
'''

# BRC
[[all]]
opcode = "brc"
dst = "Any"
src1 = "Any"
src2 = "Any"
translation = '''
add {1} {b} {c}
brl {a} {1} {b}
brl {a} {1} {c}
'''

# BNC
[[all]]
opcode = "bnc"
dst = "Any"
src1 = "Any"
src2 = "None"
translation = '''
lod {1} {b}
str {a} {1}
'''
